### ISSUE TITLE
Fail to open

### ISSUE THREAD

**Issue by Jtporter9** [romgrk/termrk#71] opened 2016-02-12 20:58 UTC
termrk is failing to open (alt-space) never had an issue until recent update. seems to be V - 0.2.0

**Comment by romgrk** [comment] 2016-02-12 22:27
Oh damn, it was real then! I taught it was just me. I'll post a patch later. In the meantime I have it working here by specifically mapping `alt-space` in `keymap.cson`.

**Comment by romgrk** [comment] 2016-02-12 22:48
Okay. So I pushed already to cause no more disruption than needed, as this was pretty straight-forward: https://github.com/romgrk/termrk/commit/f8ba36b14b8445b4ed60e28509832abaae38140e.

This was caused by a setting implemented to disable the default termrk keymap (although I should have check not to change anything!). 
As it has been made void by recent updates to the Atom Keymap Manager, it is simply removed.

Let me know if there's anything!

**Comment by exside** [comment] 2016-11-17 19:48
it's strange, I had everything working with alt-space under OS X 10.10.5, updated to macOS Sierra 10.12.1 and now alt-space doesn't do anything anymore, I reinstalled termrk, checked the keybindings (they are present) but can't get it to work...any suggestions?

I just checked with the keybinding resolver, all fine, when pressing alt-space it shows up and termrk:toggle is triggered, but nothing happens, no sliding up panel =/...

when I uninstalled termrk at first (to reinstall) I had to install the XCode commandline tools (did via "xcode-select --install" ... had to install again, had them under 10.10), but then the installation went trough, but still wasn't working

UPDATE: Investigating this further (I got really used to my terminal slide in panel in atom^^...miss it) I found via dev tools console the following warning:

```
Failed to require the main module of 'Termrk' because it requires one or more incompatible native modules (pty.js).
Run `apm rebuild` in the package directory and restart Atom to resolve.
```

which is what I did, e.g.:

```
cd ~/.atom/packages/Termrk
apm rebuild
```

that successfully ran, then I restarted Atom, but still nothing happens when pressing alt-space and when I open the dev tools I see the same error...also after the rebuild.

UPDATE: The issue seems to be pty.js and not only for Termrk, see https://github.com/jeremyramin/terminal-plus/issues/311#issuecomment-237317386

UPDATE: https://atom.io/packages/platformio-ide-terminal looks and works very similar to termrk and it works in macOS Sierra 10.12.1 and Atom 1.2.x

**Comment by romgrk** [comment] 2016-11-30 04:00
Just inspected this, platformio seems to solve it by using a self-provided prebuilt pty.js. This is their package.json deps:
```json
  "dependencies": {
    "atom-space-pen-views": "^2.1.0",
    "pty.js": "https://github.com/platformio/pty.js/tarball/prebuilt",
    "term.js": "https://github.com/jeremyramin/term.js/tarball/master",
    "underscore": "^1.8.3"
  }
```

Could you try to change the dependency in the Termrk `package.json` to check if it works with the above one? Replace line 29, 
```
    "pty.js": "0.3.1",
```
with
```
    "pty.js": "https://github.com/platformio/pty.js/tarball/prebuilt",
```

**Comment by romgrk** [comment] 2016-11-30 04:05
Closing this because it is a different issue, please kindly report any update in https://github.com/romgrk/termrk/issues/94 :)

**Closed as completed by romgrk** 2016-11-30 04:05 UTC
